version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - pip install mkdocs
      - mkdocs --version
      - pip install mkdocs-material
      - pip install markdown-fenced-code-tabs
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cd my-project
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mkdocs build
#      - aws s3 rsync site/ s3://$BUCKET --delete
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
  artifacts:
    files:
      - my-project/site/**/*
#      discard-paths: yes
#      base-directory: location
